version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Composer"
      include: "scope"
    versioning-strategy: increase
    groups:
      wordpress:
        patterns:
          - "roots/wordpress"
          - "koodimonni-language/core-nl_nl"
      symfony-polyfill:
        patterns:
          - "symfony/polyfill*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Github-actions"
      include: "scope"
