
services:
  dbserver:
    image: mariadb:10.11.4
    container_name: dbserver
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    #Only used for initialization
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: muziekpraktijkvivo
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspwd

  webserver:
    build: .
    image: muziekpraktijkvivo-website:latest
    container_name: webserver
    ports:
      - 80:80
    # volumes:
    #   - ./public_html/uploads:/var/www/html/uploads
    environment:
      - DB_HOST=dbserver
      - DB_USER=wordpress
      - DB_PASSWORD=wordpresspwd
      - DB_NAME=muziekpraktijkvivo
      - DB_PREFIX=wp_www_
      - WP_ENVIRONMENT_TYPE=development
      - WP_HOME=http://localhost
      - WP_SITEURL=http://localhost/core

volumes:
  mariadb: